on:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull-request
        run: |
          gh pr create --title "Update devel branch" --body "This PR updates changes in main branch" --repo ${{ github.repository }} --base devel --head main
