on:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: devel
      - name: Promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - uses: peter-evans/create-pull-request@v5
        name: Create Pull Request
        with:
          branch: update/devel
          reviewers: saorio
          title: Update devel branch
          body: |
            This PR updates the devel branch with the latest changes from main.
          delete-branch: false
