on:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: peter-evans/create-pull-request@v5
        name: Create Pull Request
        with:
          branch: update/devel
          base: devel
          reviewers: saorio
          title: Update devel branch
          delete-branch: true
