name: Renovate
on:
  schedule:
    - cron: '0 9 4 * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: ./renovate-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
